- hosts: all
  remote_user: root

  tasks:
  - name: Установка пакетов на Ubuntu
    apt: pkg={{ item }} state=latest
    with_items:
      - rsync
      - wget
      - nano
      - atop
    when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'

  - name: Установка пакетов на CentOS
    dnf: pkg={{ item }} state=latest
    with_items:
      - atop
      - bind-utils
      - man
      - mc
      - nano
      - net-tools
      - ntp
      - rsync
      - smartmontools
      - perl
      - pwgen
      - tcpdump
      - wget
    when: ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat Enterprise Linux'

  - name: Запуск службы и включение на CentOS
    ansible.builtin.systemd: 
      name: nginx
      state: started
      enabled: yes

  - name: Остановка и отключение службы на CentOS
    ansible.builtin.systemd:
      name: firewalld
      state: stopped
      enabled: no
                                    
  - name: Остановка сервиса на Ubuntua
    ansible.builtin.service:
    name: httpd
    state: stopped
