- name: Ping Servers
  hosts: local_oracle
  become: yes
  tasks:
  - name: Update cache
    dnf:
      update_cache: yes

  - name: Upgrade all
    ansible.builtin.dnf:
      name: "*"
      state: latest

  - name: Install htop
    ansible.builtin.dnf:
      name: htop
      state: latest
  
  - name: Copy test file
    copy:
      src: ./test_file.txt
      dest: /home/
      mode: 0777